
apiVersion: v1
kind: Service
metadata:
  name: hkn-observability
  namespace: test
  labels:
    app: hkn-observability
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hkn-observability